# Nginx Server
web:
  image: ecomgems/nginx
  ports:
    - "80:80"
  volumes:
    - ./src:/var/www
    - ./src/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
  links:
    - php

# PHP-FPM First App
php:
  image: nmcteam/php56
  volumes:
    - ./src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./src:/var/www
  links:
    - mysql

# MySQL
mysql:
  image: sameersbn/mysql
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql:/var/lib/mysql
  environment:
    - DB_REMOTE_ROOT_NAME=root
    - DB_REMOTE_ROOT_PASS=pass
    - DB_REMOTE_ROOT_HOST=%
